# Generated by Django 3.2.4 on 2021-06-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AthletesEvents',
            new_name='Athletes',
        ),
    ]
