# Generated by Django 3.2.4 on 2021-06-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0002_rename_athletesevents_athletes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athletes',
            options={'verbose_name_plural': 'athletes'},
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_event',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_games',
            new_name='games',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='id_athlete_event',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_medal',
            new_name='medal',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_noc',
            new_name='noc',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_season',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_sport',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='athlete_year',
            new_name='year',
        ),
    ]
