# Generated by Django 3.2.4 on 2021-06-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0003_auto_20210608_2245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Athletes',
            new_name='Athlete',
        ),
    ]
