# Generated by Django 3.2.4 on 2021-06-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0004_rename_athletes_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='event',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='games',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='medal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='noc',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='season',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sport',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
