# Generated by Django 3.2.4 on 2021-06-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0005_auto_20210609_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
