# Generated by Django 3.2.4 on 2021-06-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0006_auto_20210609_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='medal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='noc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='season',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
