# Generated by Django 3.2.4 on 2021-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0007_auto_20210609_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
