# Generated by Django 3.2.4 on 2021-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0010_alter_athlete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='event',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
