# Generated by Django 3.2.4 on 2021-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_events', '0011_alter_athlete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='event',
            field=models.TextField(null=True),
        ),
    ]
